export const COOKIE_RECEIVED = 'scaaf_received'
export const COOKIE_AFFILIATE_ID = 'scaaf_aid'
export const COOKIE_AFFILIATE_HASHCODE = 'scaaf_hc'
export const COOKIE_CLICK_TIME = 'scaaf_c_c'
export const COOKIE_CLICK_SOURCE = 'scaaf_sca_source_secomus'
export const COOKIE_TRACKING_ID = 'scaaf_tid'
export const COOKIE_EXPIRES_TIME = 'scaaf_ep'
export const COOKIE_AFFILIATE_NAME = 'scaaf_afn'
export const COOKIE_AFFILIATE_FIRST_NAME = 'scaaf_affn'
export const COOKIE_AFFILIATE_COMPANY = 'scaaf_afc'
export const COOKIE_AFFILIATE_PERSONAL_DETAIL = 'scaaf_pd'
export const COOKIE_ENABLE_ASSIGN_DOWN_LINE = 'scaaf_ass_dl'
export const COOKIE_UPPROMOTE_CART_TOKEN = 'scaaf_ctk'
export const COOKIE_APPLIED_COUPON = 'sca_coupon'

// CUSTOMER REFERRAL
export const COOKIE_CUSTOMER_REFERRAL_LINK = 'scaaf_refer_customer_link'
export const COOKIE_IS_CUSTOMER_REFERRAL_PROGRAM = 'scaaf_is_program_customer'
